services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $deeplApiKey: '%env(DEEPL_API_KEY)%'
            $activeLanguageResolver: !tagged_iterator deepl.resolver

    Guave\DeeplBundle\:
        resource: ../../../src
        exclude: ../../../src/{Entity,Migrations,Resources,Tests}

    Guave\DeeplBundle\Controller\:
        resource: ../../../src/Controller
        tags: [ 'controller.service_arguments' ]
        public: true

    Guave\DeeplBundle\EventListener\LoadFallbackTranslationsListener:
        public: true

    Guave\DeeplBundle\Resolver\ActiveLanguageByDCMultilingualResolver:
        public: true
        tags:
            - { name: 'deepl.resolver', priority: 20 }

    Guave\DeeplBundle\Resolver\ActiveLanguageByPageOrArticleOrArticleContentResolver:
        public: true
        tags:
            - { name: 'deepl.resolver', priority: 19 }

    Guave\DeeplBundle\Resolver\ActiveLanguageByNewsContentLanguageResolver:
        public: true
        tags:
            - { name: 'deepl.resolver', priority: 18 }

    Guave\DeeplBundle\Resolver\ActiveLanguageByNewsLanguageResolver:
        public: true
        tags:
            - { name: 'deepl.resolver', priority: 17 }

    Guave\DeeplBundle\Resolver\ActiveLanguageByNewsArchiveLanguageResolver:
        public: true
        tags:
            - { name: 'deepl.resolver', priority: 16 }

    Guave\DeeplBundle\Config\Config:
        public: true

    Guave\DeeplBundle\Translate\TranslateDCA:
        public: true

