services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $deeplApiKey: '%env(DEEPL_API_KEY)%'

    Guave\DeeplBundle\:
        resource: ../../../src
        exclude: ../../../src/{Entity,Migrations,Resources,Tests}

    Guave\DeeplBundle\Controller\:
        resource: ../../../src/Controller
        tags: [ 'controller.service_arguments' ]
        public: true

    Guave\DeeplBundle\EventListener\LoadFallbackTranslationsListener:
        public: true
